# 1. Import Libraries

In [19]:
import os
import numpy
import pandas
import openpyxl
from sklearn.covariance import EllipticEnvelope

# 2. Set Directory and Dataset

In [22]:
# 1. Function to declare path
def declare_path() : 
    main_dir = f"D:\\Freelance Data Scientist"
    data_dir = os.path.join(main_dir,f'202410\\01_Analisis TryOut UTBK')

    return main_dir, data_dir

# 2. Funtion to call dataset
def call_dataset(data_dir, file_name) :
    
    if file_name.endswith("xlsx") :
        df = pandas.read_excel(os.path.join(data_dir,file_name))
    elif file_name.endswith(".csv") :
        df = pandas.read_csv(os.path.join(data_dir,file_name))
    else :
        print("Unsupported Format!")

    return df

# 3. Running the syntax
main_dir, data_dir = declare_path()
df_tryout = call_dataset(data_dir=data_dir, file_name="dataset_tryout.xlsx")

# Display our dataset
display(df_tryout)

,user_id,full_name,email,title,tps,Penalaran Kuantitatif,Literasi Bahasa Indonesia,Literasi Bahasa Inggris,Penalaran Matematika,Pemahaman Bacaan & Menulis,Pengetahuan & Pemahaman Umum,Pengetahuan Kuantitatif,Penalaran Induktif,Penalaran Deduktif,Rata - rata
0,541122,Aulia Nur Rahmawati,murid150@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,300,433,216,766,1232,1197,666,466,700,664.000000
1,541120,Aisyah,murid149@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,600,566,350,500,850,450,666,500,900,598.000000
2,541132,Icha Septiliasandy,murid155@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,300,433,897,383,716,349,666,400,1332,608.444444
3,541140,Muhammad Aksan Rasya Irawan,murid159@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,900,0,0,0,616,1947,533,600,600,577.333333
4,541128,Dico Ferdiyanto,murid153@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,800,433,299,433,566,649,600,566,500,538.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,540960,Elsa Aprilia Putri,murid69@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,0,244,83,150,0,0,0,0,0,53.000000
221,629257,Mahesa danu wijaya,murid230@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,200,0,0,0,0,0,0,100,66,40.666667
222,540974,jihan aliana,murid76@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,0,0,0,216,0,0,0,0,0,24.000000
223,540956,Aulia adwaya,murid67@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,0,0,0,0,0,0,0,0,0,0.000000
224,541054,Khumaira Ulva Nadziva,murid116@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,0,0,0,0,0,0,0,0,0,0.000000

# 3. Detecting Outliers

In [25]:
"""
We will use Elliptic Envelope Method
It's also derivation of Gaussian Elliptical Method
"""

# 1. Create Elliptic Envelope's Function
def elliptic_envelope(data, list_columns, contamination=0.1, save_file=False) :

    # Extract the numerical data for analysis
    X = data[list_columns].values

    # Fit Elliptic Envelope Model
    envelope = EllipticEnvelope(contamination=contamination)
    envelope.fit(X)

    # Predict the outliers and calculate scores
    outliers = envelope.predict(X)
    scores = envelope.decision_function(X)

    # Add a column to identify outliers and scores
    data['Outliers'] = outliers
    data['Elliptic Score'] = scores

    # Create two seperate dataframes
    data_outliers = data[data["Outliers"] == -1].copy()
    data_cleaned = data[data["Outliers"] == 1].copy()

    # Saving both dataframe
    if save_file == True :
        data_outliers.to_excel(os.path.join(data_dir, "dataset_outliers.xlsx"))
        data_cleaned.to_excel(os.path.join(data_dir, "dataset_cleaned.xlsx"))

    return data_outliers, data_cleaned

# 2. Run the syntax
list_columns = [
    'Penalaran Kuantitatif', 'Literasi Bahasa Indonesia', 'Literasi Bahasa Inggris',
    'Penalaran Matematika', 'Pemahaman Bacaan & Menulis', 'Pengetahuan & Pemahaman Umum',
    'Pengetahuan Kuantitatif', 'Penalaran Induktif', 'Penalaran Deduktif'
]

df_outliers, df_cleaned = elliptic_envelope(data = df_tryout, list_columns=list_columns,
                                            contamination=0.1, save_file=True)

# 3. Displaying outliers data
display(df_outliers)

,user_id,full_name,email,title,tps,Penalaran Kuantitatif,Literasi Bahasa Indonesia,Literasi Bahasa Inggris,Penalaran Matematika,Pemahaman Bacaan & Menulis,Pengetahuan & Pemahaman Umum,Pengetahuan Kuantitatif,Penalaran Induktif,Penalaran Deduktif,Rata - rata,Outliers,Elliptic Score
0,541122,Aulia Nur Rahmawati,murid150@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,300,433,216,766,1232,1197,666,466,700,664.000000,-1,-39.438121
2,541132,Icha Septiliasandy,murid155@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,300,433,897,383,716,349,666,400,1332,608.444444,-1,-61.686500
3,541140,Muhammad Aksan Rasya Irawan,murid159@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,900,0,0,0,616,1947,533,600,600,577.333333,-1,-175.063603
8,540916,Ilyas Nugroho,murid47@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,300,377,583,1032,416,649,466,66,533,491.333333,-1,-26.995872
10,540840,Dimas Kianta Putra,murid9@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,100,411,266,216,483,449,1466,233,500,458.222222,-1,-102.978497
12,541144,Muhammad Zami Arham,murid161@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,100,0,0,0,583,1947,400,500,466,444.000000,-1,-206.828778
20,541136,Laila Zhaira Sahwa,murid157@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,500,277,699,366,283,399,800,166,200,410.000000,-1,-10.990311
21,540838,Dhaffa Zainal Arifin,murid8@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,400,266,399,83,283,216,400,133,1500,408.888889,-1,-85.577448
26,540922,Keysha Shifa Hafizhah,murid50@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,500,299,416,116,1197,149,66,266,533,393.555556,-1,-56.336540
28,540934,Restu althafunnisa,murid56@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,400,222,699,0,948,249,200,366,400,387.111111,-1,-28.007752
31,540848,galang damar rajendra,murid13@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,300,432,133,133,316,233,798,233,866,382.666667,-1,-4.034203
32,540900,Farrel Herbie Al-Ayyubi,murid39@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,200,277,149,283,433,299,133,66,1599,382.111111,-1,-98.510343
39,541130,Fahrun Nasywa Jilan Amany Nur Syahida,murid154@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,500,0,0,0,299,299,1398,333,433,362.444444,-1,-95.888035
41,629221,Amanda Hayyu Lukita,murid212@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,300,255,66,100,416,266,1200,200,433,359.555556,-1,-47.684036
45,540906,Ganendra a.p,murid42@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,200,266,133,149,166,433,333,66,1398,349.333333,-1,-59.478386
46,540914,ILHAM COKRO WIBOWO,murid46@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,100,144,566,100,283,1047,600,66,233,348.777778,-1,-37.705237
51,540834,Ayunda Cinde Aruming Ratri,murid6@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,0,366,0,0,566,133,333,0,1599,333.000000,-1,-140.252969
53,540892,Faathihah Nadhiifah Nur Aziizah,murid35@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,200,266,1248,166,299,66,200,200,300,327.222222,-1,-81.071522
54,541160,Anisa Rahma Fauziah,murid169@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,400,199,166,83,183,133,999,300,433,321.777778,-1,-16.787886
59,541184,M. Surya P,murid181@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,0,866,216,83,366,249,200,300,533,312.555556,-1,-0.854311
91,629227,Andika dwi pangestu,murid215@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,200,111,1149,83,199,133,133,100,266,263.777778,-1,-74.774302
112,541008,Ahnaf Fauzi Ashriyan,murid93@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,100,0,0,0,0,948,200,266,566,231.111111,-1,-29.251093
131,541114,Zein Fahad H,murid146@smasmuhammadiyah2surakarta.kp.id,TRY OUT 1 PTN,YES,0,333,149,166,0,0,0,1200,0,205.333333,-1,-74.833334